defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Christian Ezeani
subtitle: Full-Stack Developer

# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: CV
    link: /CV_Jiuhong_Xiao
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/jiuhong-xiao-01bb4a1a1/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/xjh19971
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/profile.php?id=100014941903366
    icon: fab fa-facebook-square

  - name: twitter
    link: https://twitter.com/xjh19971
    icon: fab fa-twitter

# Google Analytics
google_analytics: UA-158774299-1
    
