defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Jiuhong Xiao
subtitle: Master Student of Computer Science
description1: Courant Institute of Mathematical Sciences
description2: New York University

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: CV
    link: /Jiuhong_Xiao_CV.pdf
    icon: ""

  - text: Transcript
    link: /NYU_Transcript.pdf
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/jiuhong-xiao-01bb4a1a1/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/xjh19971
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/profile.php?id=100014941903366
    icon: fab fa-facebook-square

  - name: twitter
    link: https://twitter.com/xjiuhong
    icon: fab fa-twitter

# Google Analytics
google_analytics: UA-158774299-1
    
